import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import BackToTop from "@/components/backtotop/backToTop";
import Setting from "@/components/setting/setting";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <Setting />
        {children}
        <BackToTop />
    <Footer />
      </body>
    </html>
  );
}
